### ISSUE TITLE
数据监听器的文档中有一点不太理解

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/glass-easel#10]
[here](https://github.com/wechat-miniprogram/glass-easel/blob/master/glass-easel/guide/zh_CN/data_management/data_observer.md#:~:text=//%20%E6%95%B0%E6%8D%AE%E7%9B%91%E5%90%AC%E5%99%A8%E4%B8%AD%EF%BC%8C%E6%9C%80%E5%A5%BD%E4%BD%BF%E7%94%A8%20updateData%20%E8%80%8C%E9%9D%9E%20setData%0A%20%20%20%20%20%20//%20%EF%BC%88%E4%BA%8B%E5%AE%9E%E4%B8%8A%EF%BC%8C%E4%BD%BF%E7%94%A8%20setData%20%E5%B0%86%E4%B8%8E%20updateData%20%E7%AD%89%E6%95%88%EF%BC%89)

**Comment by LastLeaf** [comment]
确实这里忘了解释 `updateData` 相关的问题，可能需要仔细阅读 [高级数据更新方法](https://github.com/wechat-miniprogram/glass-easel/blob/master/glass-easel/guide/zh_CN/data_management/advanced_update.md) 才能理解。

我看看怎么优化下文档。
