### ISSUE TITLE
[bug] model 双向绑定在 webview 渲染模式失效

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#126]
问题详情见：
https://github.com/xiaweiss/miniprogram-bug-report/issues/206

或者社区反馈帖子：
https://developers.weixin.qq.com/community/minihome/doc/000624e7084b20b33df00efa761000

**Comment by LastLeaf** [comment]
目前 glass-easel 还没有 landing 到 webview 渲染模式中。这种渲染模式其实是将 glass-easel 部分运行在旧框架上。

这并不是 glass-easel 本身的问题，而是 glass-easel 和旧框架之间交互有点问题。

**Comment by LastLeaf** [comment]
具体 bug 原因已经确认，已提交给相关模块。

**Comment by xiaweiss** [comment]
@LastLeaf 又出现相同的问题了，另一个 case 稳定复现
https://github.com/wechat-miniprogram/glass-easel/issues/143
