### ISSUE TITLE
[bug mac] input 框 placeholder 和 value 错误的同时显示了

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#128]
see: https://github.com/xiaweiss/miniprogram-bug-report/issues/203

**Comment by LastLeaf** [comment]
与 glass-easel 无关。已提交相关同事。

**Comment by xiaweiss** [comment]
关闭 glass-easel 后就回复正常了，具体什么情况？

**Comment by xiaweiss** [comment]
Skyline 1.2.0 更新日志，显示修复了，但问题还在，就很疑惑。
我在微信 skyline 社区发帖了，后续在帖子里跟进吧。https://developers.weixin.qq.com/community/minihome/doc/00064ccb130570e496f0938f56b000

**Comment by LastLeaf** [comment]
同事反馈说是已经发布了。估计需要等等更新。
