### ISSUE TITLE
[glass-easel] model 双向绑定在 webview 渲染模式失效？

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#129]
代码片段：https://developers.weixin.qq.com/s/HPI1CWmz7eNW

这个问题会影响 PC 以及降级到 webview 渲染模式的表现

见帖子：https://developers.weixin.qq.com/community/minihome/doc/000624e7084b20b33df00efa761000

**Comment by LastLeaf** [comment]
和 #126 一样吗？

**Comment by LastLeaf** [comment]
Closed as #126 。
