### ISSUE TITLE
[bug] model 双向绑定在 webview 渲染模式失效 2

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#143]
代码片段：https://developers.weixin.qq.com/s/okn5YhmF7EQO

另外如果组件名，变量名，都是一个单词，没有驼峰、连字符，表现是正常的。

期望点击 toggle 按钮时，能够切换列表数量，实际无法切换。关闭 glass-easel 后可以正常切换

以前修复过的相关 case：https://github.com/wechat-miniprogram/glass-easel/issues/126

**Comment by xiaweiss** [comment]
郑树诚在看，估计是编译的问题

**Comment by LastLeaf** [comment]
与上一个问题一样，这并不是 glass-easel 本身的问题，而是 glass-easel 和旧框架之间交互有点问题。不在这里处理。

已经定位到问题。

**Comment by xiaweiss** [comment]
好的，目前关闭 glass-easel 就能恢复正常，用户侧无法分清楚内部什么问题，所以我只能提交到这里来。

**Comment by xiaweiss** [comment]
2024年8月26日，测试已修复
