### ISSUE TITLE
【bug】[glass-easel] model 双向绑定在 webview 渲染模式失效

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#151]
4月7日发现新的有问题 case：

代码片段：https://developers.weixin.qq.com/s/okn5YhmF7EQO

另外如果组件名，变量名，都是一个单词，没有驼峰、连字符，表现是正常的。

期望点击 toggle 按钮时，能够切换列表数量，实际无法切换。关闭 glass-easel 后可以正常切换

**Comment by xiaweiss** [comment]
此问题已经 1 个月没有人处理了，最新的基础库 3.4.4 也异常。请看下具体是哪个部门修改？

**Comment by LastLeaf** [comment]
如果与 #127 一致，请不要重复提交问题。

同事反馈相关修复尚未上线。

**Comment by LastLeaf** [comment]
如果与 https://github.com/wechat-miniprogram/glass-easel/issues/143 一致，请不要重复提交问题。

同事反馈相关修复尚未上线。

**Comment by xiaweiss** [comment]
@LastLeaf 问题长期无法解决，希望可以留着 issue，等解决后再关闭。

**Comment by xiaweiss** [comment]
算了，后续的所有问题，我不再这边反馈了。单独在微信群里反馈吧。打扰了。

**Comment by xiaweiss** [comment]
补充一下：现在 glass-easel 和小程序编译，对普通用户来说，是个黑盒。

用户只知道开启了 glass-easel 就出问题了，不开就没事。至于里面的细节，具体是哪里的问题，是无法判断的。用户的第一反应，就是 glass-easel 的”问题“，这么看来，在这里提 issue 似乎没什么问题。

另一方面编译问题，并没有任何仓库可以反馈。

**Comment by LastLeaf** [comment]
如果遇到相同问题未能解决或再次出现，应 reopen 之前的 issue 并在那里说明原因。

如果怀疑是 glass-easel 的问题，可以提交到这里。已确认的非 glass-easel 的问题，且有微信群等其他方式可以提交的话，不要提交到这里。

**Comment by xiaweiss** [comment]
我没有权限 reopen，不是针对你个人哈，现在 skyline 的各种问题，修复周期都很长，很多都以月为单位了。
目前无法得到有效反馈，无法知道问题是否修复 =_=

我现在只能用自己的仓库记录，然后定期回归测试的方式来验证：
https://github.com/xiaweiss/miniprogram-bug-report/issues

后续我在微信群反馈吧，也避免重复提问打扰。

**Comment by LastLeaf** [comment]
Sorry 没注意到 github 的 reopen 权限控制差异。不过直接 comment 也会有消息提示的，有疑问的话不需要 reopen 。

其他微信小程序相关问题请走其他沟通渠道，否则遇到我也不认识 maintainer 的模块的话，我也会很尴尬 😂
