### ISSUE TITLE
[bug] ios 真机小程序白屏无法加载

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#31]
版本：iphone12，iOS 16.4.1 ，微信 8.0.36，基础库 2.31.0
使用开发者工具 mac 1.0.6.2304212 运行正常

页面有配置全局组件 usingComponents、只在后面的页单独开启了 "renderer": "skyline", "componentFramework": "glass-easel"

使用工具启动真机预览小程序，进主页就报错了。主页是 webview 模式

![IMG_7447](https://user-images.githubusercontent.com/17960084/233825676-392c7d65-472a-4fc4-8684-903635a4cffd.PNG)

**Comment by LastLeaf** [comment]
并不是 glass-easel 本身的 bug 。

已经和同事确认是预览触发的编译过程有问题，需要 miniprogram compiler 上线修复。

**Comment by xiaweiss** [comment]
好的，谢谢
