### ISSUE TITLE
Variables in the template `trueText` `nullText` raise Template parsing error

### ISSUE THREAD

**Issue by phyng** [wechat-miniprogram/glass-easel#37]
If variables in the template start with true/false/null (`<text>{{ trueText }}</text>`), it will cause a syntax error.

Test: 

https://npm.runkit.com/glass-easel-template-compiler

Code:

```js
const glassEaselTemplateCompiler = require("glass-easel-template-compiler")
const g = new glassEaselTemplateCompiler.TmplGroup()
g.addTmpl('/path', '<text>{{ trueText }}</text>')
console.log(g.getTmplGenObjectGroups())
```

Return:

```text
"Template parsing error (from line 1 column 14 to line 1 column 14) : Unexpected character"
```

It should be related to the syntax definition of this file:
https://github.com/wechat-miniprogram/glass-easel/blob/1874b8d2099ec62364113be76f3939b81a10a6e7/glass-easel-template-compiler/src/tmpl.pest

**Comment by LastLeaf** [comment]
There is a bug when parsing template keywords with pest.
