### ISSUE TITLE
chaining API在实践复杂应用中还是会有逻辑拆分的问题，有没有考虑加上Composition API的支持？

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/glass-easel#6]
类似react的函数组件，减少声明周期，但从框架层面提供类似useHooks的机制？

**Comment by dhlolo** [comment]
补充一点，chaining API的一般被用来本身具有链式逻辑关系(比如时序)的设计中，而改掉小程序组件的Option API的目标从应用开发者的角度应该是带来更好的逻辑组织形式，并不符合此处的目的(当然如果说从实现难度和兼容老板本的基础库实现，可能更让人接受一些)。至于Composition API的建议，从js应用开发框架生态来说，好处不必说了，相关可以看看vue2 -> vue3尤雨溪的一些演讲。

**Comment by LastLeaf** [comment]
我不太理解你说的“链式逻辑关系”指的是什么。可能你的理解不太正确。

Chaining API 设计上类似于另一种形式的 behavior 。例如：

```
componentSpace.define()
  .xxx()
  .yyy()
  .registerComponent()
```

可以被进一步抽象为：

```
const someLogic = (componentSpace) => componentSpace.define().xxx()

someLogic.yyy().registerComponent()
```

当然，维持链式写法的话直接用 behavior 就好了：

```
const behavior = componentSpace.define()
  .xxx()
  .registerBehavior()

componentSpace.define()
  .behavior(behavior)
  .yyy()
  .registerComponent()
```

本质上说，和 hooks / composition API 是类似的，都是在组件的定义期进行逻辑组合的机制，但又与它们都不太一样。需要注意的是，它并不是在组件的实例化期间执行的，链式调用中各个调用的顺序没有太大影响。

除此以外，设计这个接口的另一个目的是提供更好的 TypeScript 类型推断支持。

这种接口形式其实非常类似于 rust 的 [builder pattern](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) ，如果你熟悉这个的话就很好理解了。

**Comment by LastLeaf** [comment]
另外，结合 init 函数可以做到一些更独特的事情。

```
componentSpace.define()
  .init(function ({ lifetime, setData }) {
    ...
  })
  .registerBehavior()
```

从某种角度来说 init 函数才更像 hooks / composition API 。但这里加入 init 函数的目的主要还是为了减少对 this 的依赖从而实现更好的 typing 支持。

**Comment by LastLeaf** [comment]
首先这里和 链式逻辑关系 并没有什么关联，它实际上几乎是执行顺序无关的。运行时，链式调用只在注册组件时执行一次（为了降低总体开销），在此次执行后会搜集所有链式调用内容（并进行注册期优化），一并用于后期的实例创建。这就非常接近于 builder pattern ，但与 promise 就差得比较远了；链式调用作为一种语法形式和 OOP 也没有必然的关联。至于“令构造变得更复杂”，其实是因为在构造复杂对象、尤其是各种字段都可选的对象的时候，就没有很简单的做法，当然会比构造简单对象更复杂。

至于为什么不用 class ，是考虑到 js 的 class 语法不太够用。

实践上 chaining API 的逻辑内聚能力与 hooks / composition API 相当。

```
componentSpace.define()
  // 1.
  .property('a', ...)
  .init(function () {
    ...
  })
  // 2.
  .property('b', ...)
  .init(function () {
    ...
  })
  .registerComponent()
```

当然，至于模仿已有框架来减少“上手成本”，我并不认为是什么恰当的做法。第一，不可能与所有已有框架都很像；第二，小程序框架要求 API 稳定性比普通框架更高。

**Comment by dhlolo** [comment]
> 首先这里和 链式逻辑关系 并没有什么关联，它实际上几乎是执行顺序无关的。运行时，链式调用只在注册组件时执行一次（为了降低总体开销），在此次执行后会搜集所有链式调用内容（并进行注册期优化），一并用于后期的实例创建。这就非常接近于 builder pattern ，但与 promise 就差得比较远了；链式调用作为一种语法形式和 OOP 也没有必然的关联。至于“令构造变得更复杂”，其实是因为在构造复杂对象、尤其是各种字段都可选的对象的时候，就没有很简单的做法，当然会比构造简单对象更复杂。
> 
> 至于为什么不用 class ，是考虑到 js 的 class 语法不太够用。
> 
> 实践上 chaining API 的逻辑内聚能力与 hooks / composition API 相当。
> 
> ```
> componentSpace.define()
>   // 1.
>   .property('a', ...)
>   .init(function () {
>     ...
>   })
>   // 2.
>   .property('b', ...)
>   .init(function () {
>     ...
>   })
>   .registerComponent()
> ```
> 
> 当然，至于模仿已有框架来减少“上手成本”，我并不认为是什么恰当的做法。第一，不可能与所有已有框架都很像；第二，小程序框架要求 API 稳定性比普通框架更高。

- class的语法不太够用可以细说一下么
- “模仿已有框架，来降低上手成本” 不是耻辱，vue也没有否认对react hooks的模板，难道他们在前端界的口碑和表现没有小程序框架好么。。还是说API稳定性比小程序差？？事实可能恰好相反。
- 顶层API的易用性设计，和底层运行时框架稳定性之间还是有很多层的。我理解本仓库只是理清运行时组件组织和解析的逻辑，独立于运行时后端的同事，尝试提出一种新的应用代码组织形式。如果组织形式真有一天要面向众多开发者，那API易用性还是相当重要的指标的，这点可能也是之前小程序一直被诟病的原因之一。

**Comment by LastLeaf** [comment]
> class的语法不太够用可以细说一下么

因为 class 里面只有数据和方法两类字段，其表达能力显然是弱于组件字段所需要的表达能力的。而且抛弃掉 class 的约束之后还能做到更多的事情。

当然也是有代价的：对 TypeScript 编译性能有负面影响。不过目前看来还可以接受。

> vue也没有否认对react hooks的模板

vue 与 react hooks 的相似程度也不算很高吧，也许实质上还不及 chaining API 与 composition API 的相似程度。其实你看我上面的描述应该也能感觉到我们实际上是有在模仿的，只是实际表现出来的表面接口差异看起来比较大。至于为什么表面接口差异更大，一是需要比较好的向前兼容、需要两种 API 形式的互动，二是小程序环境需要更多注册期优化。

另外，出于深层机制的原因，也不太可能模仿哪个模仿得很像，综归会有区别的。抄个变量名、方法名也没什么意思吧？

> 还是说API稳定性比小程序差

抱歉我的表述可能有点偏差，这里指的“稳定性”主要指向前兼容性。我们只允许非常有限的破坏性变更，几乎不允许主版本升级。这使得我们即使模仿某个框架的某个特定版本，也不能保证去模仿它的后续版本。

至于稳定性方面：在我看来，小程序 API 稳定性看起来更差主要是因为整体的小程序 SDK API 实在是太多了、远多于组件框架本身。（这个也不是我们能够为稳定性 bug 狡辩的理由，对不起！）无论是不是这个原因，作为组件框架一方，我们都不能降低对 API 稳定性和向前兼容的追求。

> 本仓库只是理清运行时组件组织和解析的逻辑，独立于运行时后端的同事，尝试提出一种新的应用代码组织形式

其实我们也没有这么高的“立意”，遇到问题解决问题罢了。主要目的当然还是为了继承和扩展小程序组件框架的特性集、通过重构来优化代码，并使得部分小程序代码能脱离小程序环境运行（且具有较优的性能表现）。

（当然我们其实也在实现一些自定义后端，这是后话了。）

> 顶层API的易用性设计，和底层运行时框架稳定性之间还是有很多层的。

> API易用性还是相当重要的指标的

这里确实得承认以往组件框架实现时确实是更倾向于稳定性、向前兼容和性能表现，而在接口设计上关注度相对较低。感谢你对接口设计方面的关注！

在这方面，我们未来还会继续优化 typing 和 IDE 支持等方面。不过，鉴于上面说过的理由，我觉得 chaining API 应该还不需要做大幅度的调整。

至于添加类似的 composition API ，其实 chaining API + init 函数 已经在实质上比较类似了，还要求它更像一些吗？如果有具体想法的话可以具体提出。

**Comment by dhlolo** [comment]
- 向前兼容性这一点提出来，别人也没办法说什么了；
- 注册期优化和运行时相关逻辑强相关，这个理由作为小程序应用开发者也没法拒绝；
- 至于`class 里面只有数据和方法两类字段` 实际上Option中也就是这两类ObjectMethod和ObjectProperty，然后各种设置吧，只是大概可以想象class可能会更难组织，更多可能没必要或过于杂乱的继承关系
- vue和react hooks相似程度还是很高的，你要说`相似程度也不算很高吧，也许实质上还不及 chaining API 与 composition API 的相似程度`，那我只能拿出vue3官方推荐的写法:
`function useMouse() {
  let x = $ref(0);
  const update = (e) => {
  x = e.pageX;
  };
  // ...setup listeners
  return $$(x);
}`
- 关于将using等字段回收到js中，或者一开始option和模板的设计，Mustache等等，在很多地方也能看到react或者vue等流行web框架思想的影子，我只想说，模仿并不可耻哈，好用才是关键，你要说chaining API能用吗？也能用啊，Option API也能用啊~

**Comment by LastLeaf** [comment]
> Option中也就是这两类ObjectMethod和ObjectProperty，然后各种设置吧，只是大概可以想象class可能会更难组织

其实就是基于这样的考虑所以就没用 class 。

> 拿出vue3官方推荐的写法...

从表面语法上看，这个我们确实没法模仿了。

> 将using等字段回收到js中

这个不是回收，原本旧的组件框架就是这样的。然而一旦结合上编译就不能这么做了（否则小程序 SDK 的一些特性没法做）。所以 glass-easel-miniprogram-adapter 依旧是分离式的。

> Mustache

这个已经不能说是模仿谁了，属于业界惯例了，历史都能追溯到十五年前左右了。

> 你要说chaining API能用吗？也能用啊

关于 chaining API 的问题，如果有具体改进意见，可以具体提出讨论。

**Comment by dhlolo** [comment]
- 虽然class对于运行时组件框架开发者可能带来更大的负担，尤其在考虑向前兼容和历史包袱的情况下;
- 但无疑class可以为应用开发者提供更优的开发体验，再结合wechatminiprogram/mobx...，或者tencent/westore等，可以提供更优雅和一贯的代码风格
`
  class ServiceA extends Service {
     fetchUserInfo: () => services.request('/get_user_info')
     fetchOption: () => services.request('/get_option')
  }

  const serviceA = new ServiceA();
  
  class StoreA extends Store {
    @observable
    options: {},
    
    @action
    async updateOptionFromOrigin() {
      const options = await serviceA.fetchOption();
      this.options = options;
    }
  }

const storeA = new StoreA();
  
  @injectStore(storeA)
  @injectService(serviceA )
 export default class ComponentA extends Component {
    @property(Object)
     value: {}
     @property(Text)
     label: ''
     data：<TData>{},
     @method
     onUpdateBtnClick() {
        this.store.updateOptionFromOrigin();
     }
  }
`

**Comment by dhlolo** [comment]
另外，如果继续沿用Chaining API，实际上还是借用behavior的方式来组合逻辑，其本质仍然是个mixin，那不可避免还是会出现下图的问题：
![image](https://user-images.githubusercontent.com/50065494/220832587-e3cee2d8-5018-4f25-ad22-c939ce0b946c.png)

**Comment by LastLeaf** [comment]
如你的例子所示（带有各种 anotation 的 class 写法），这会带来几个问题：

* 可能带来比较大的二次接口封装的运行时开销（需要注意 glass-easel-miniprogram-adapter 也是对 glass-easel 的二次接口封装），这样的开销视情况可能是不可接受的；
* 有些字段是没有真正意义上的字段名的，比如 observers 和 relation ，用这种方式表达可能会比较尴尬。

> 以这样的接口来做adaptor感觉更优雅一些，虽然实现难度显然比Chaining大了

其实我们对 chaining API 的实现恐怕并没有你想象的那么简单。

> 这对于小程序开发者，无论从表达，习惯，整洁度上，易读性上，难道没有比链式的强么

这个请证明一下。

（到目前为止我们自己的实践未发现有什么问题。 P.S. 实践中其实并不会写长链的，而是会大量结合 init 函数。）

**Comment by LastLeaf** [comment]
> 另外，如果继续沿用Chaining API，实际上还是存在Option式和Chaining的混用，而借用behavior的方式来组合逻辑，其本质仍然是个mixin，那不可避免还是会出现下图的问题： ![image](https://user-images.githubusercontent.com/50065494/220832587-e3cee2d8-5018-4f25-ad22-c939ce0b946c.png)

我们有特殊的 TypeScript 类型处理来避免 mixin 机制带来的命名空间和静态检查之类的问题。 init 函数形成的闭包也能避免很多问题。

**Comment by dhlolo** [comment]
> 如你的例子所示（带有各种 anotation 的 class 写法），这会带来几个问题：
> 
> * 可能带来比较大的二次接口封装的运行时开销（需要注意 glass-easel-miniprogram-adapter 也是对 glass-easel 的二次接口封装），这样的开销视情况可能是不可接受的；
> * 有些字段是没有真正意义上的字段名的，比如 observers 和 relation ，用这种方式表达可能会比较尴尬。
> 
> > 以这样的接口来做adaptor感觉更优雅一些，虽然实现难度显然比Chaining大了
> 
> 其实我们对 chaining API 的实现恐怕并没有你想象的那么简单。
> 
> > 这对于小程序开发者，无论从表达，习惯，整洁度上，易读性上，难道没有比链式的强么
> 
> 这个请证明一下。
> 
> （到目前为止我们自己的实践未发现有什么问题。 P.S. 实践中其实并不会写长链的，而是会大量结合 init 函数。）

- `可能带来比较大的二次接口封装的运行时开销（需要注意 glass-easel-miniprogram-adapter 也是对 glass-easel 的二次接口封装），这样的开销视情况可能是不可接受的；`
从你的语言表述逻辑上：可能带来较大开销 -> 不清楚开销是否存在，多大 -> 但是不可接受  这。。另外，注解是可以在编译时处理的，不直接套用现成的打包成wrapper，只在编译器层作为转译的，类似google closure compile的增强注解，但融合到语言里，对你们的解析器有更高的要求。最后，链式会创建更多函数调用栈，虽然每个比较小，可能也无用，只是为了闭包的传递和更好的类型提示
- `有些字段是没有真正意义上的字段名的，比如 observers 和 relation ，用这种方式表达可能会比较尴尬` 都是无意义的字段名，用这种表达不明白尴尬在哪里
- `其实我们对 chaining API 的实现恐怕并没有你想象的那么简单。` 我并没有觉得你们的实现简单，复杂也不代表是好框架，再说简单不简单我也并不关注，我只关注好用，我只是纯粹从接口设计和应用使用的角度提出一些Chaining API在易用性方面质疑
- `从表达，习惯，整洁度上，易读性上` 上要求我证明一下。。你可以做个调研，两个api的例子，让纯应用开发的使用者投票试试看。其实很好奇，你们从设计之处到现在有没有做过这种工作？

- `我们有特殊的 TypeScript 类型处理来避免 mixin 机制带来的命名空间和静态检查之类的问题。 init 函数形成的闭包也能避免很多问题。` 牛

**Comment by LastLeaf** [comment]
有关你对易用性的质疑， chaining API 其实就是在我们自己的实践中不断改进的，无论是在底层组件实现、高层组件（页面）实现、 glass-easel-miniprogram-adapter 上， chaining API 都表现出很好的易用性，在底层组件中还有很好的可控性，必要时还可以再次封装。

你可能过于重视链式写法的直观表现，确实链式写法和以往常见的函数链（无论是 rxjs promise 还是什么别的）直观含义大多都不太相同。但这也仅仅是一个链而已，抛弃对它的刻板印象、只把它单纯的看成一种写法就行。如果你对 OOP 有比较强的偏好——这种写法确实不怎么迎合 OOP 的偏好。如果接口设计范式与其他方面相矛盾，我们更倾向于后者。因为接口设计相关的偏好可以通过二次封装来加工，但后者就不一定了。

有关你对编译链路方面的问题，可能我需要进一步说明一些背景。

首先如 README 文档所言， glass-easel  **是** 小程序 SDK 内模块，而 glass-easel-miniprogram-adapter 则 **不是** 小程序 SDK 内模块。作为小程序 SDK 内模块，是不能与编译链路耦合的，因为小程序 SDK 有自己特殊的编译链路。

对于小程序代码而言，能够访问到的是 glass-easel 的 runtime 和 TypeScript 定义， runtime 是所有小程序共享的相同代码。因此小程序代码是不能通过 Closure Compiler 之类的方式与 glass-easel 联合编译的，最多只能与特制的 adapter 进行联合编译。这样，编译后的代码依旧是访问 glass-easel 的 runtime 接口，能在编译期提供的性能优化是受限的。

那么，退一步来说，能不能和 adapter 进行联合编译呢？理论上来说是可以的。不过，我们的设计是 adapter 层必须是比较薄的一层，因为用于 web 的 adapter (glass-easel-miniprogram-adapter) 和用于小程序的 adapter （这里甚至有好几个）是几份不同的代码，维护压力比较大。而且，在 adapter 层事实上也能访问到多数 glass-easel 的 low-level 接口，在这一层做优化就不是很明智。

那什么时候需要呢？我认为是做别的形式的接口封装的时候可能需要。

**Comment by LastLeaf** [comment]
现在的讨论已经太零碎了，过于陷入细节而脱离了原本的主题。

我再总结一下我之前所表述的核心观点，以及我能给出的建议。

之所以我们引入 chaining API ，主要有以下考虑：

* 向前兼容性方面， chaining API 是对 definition API 的具备相容性改进，满足小程序框架的强向前兼容性要求，且不为今后的向前兼容性保证工作增加太大负担；
* 二次接口封装方面， chaining API 相对于 definition API 更加低层，对二次接口封装更加友好、灵活和高效；
* 新特性支持方面，主要是通过与其他新特性（如 init 函数）的结合来做到，此外 chaining API 能够提供逻辑内聚、命名空间保护等重要特性；
* TypeScript 支持方面， chaining API 在部分细节上优于 definition API 。

如果你对具体的某个接口设计有疑问，可以另建 issue 讨论。

如果你更偏爱某种其他风格的 API 形式，你可以考虑另立一个独立模块、通过二次接口封装来做到。

未来我们也会考虑通过独立模块（而不是进入内核）的形式做一些接口封装的。

**Comment by dhlolo** [comment]
为啥runtime会考虑到ts友好呢？为了让框架开发者自己舒服一点么？
个人感觉运行时优化，向前兼容，面向开发优雅可以作为单独的命题，不需要都压在一层里，尤其是对开发者友好，这样很难兼顾，容易不伦不类。个人感觉既然小程序指定了一种新的面向开发者的写法，就值得为了将这种写法变严谨，做更多transform层上的事情，这个事情放因为性能不要放到core的好，则最好在adaptor制定好transform的规则。应用开发者需要的是更系统的接口，而非更底层的接口。
