### ISSUE TITLE
组件路径中的is: 'idPath'也显得有些多余

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/glass-easel#7]
个人感觉：从API角度，defineComponent时is属性显得很多余，直接将defineComponent的结果赋在using上感觉比较合理，如果是为了兼容老版本，应该也可以用babel来在编译时生成唯一id并派发到实际文件路径来解决

**Comment by LastLeaf** [comment]
首先 glass-easel 核心模块并不想与编译链路耦合。 glass-easel-miniprogram-adapter 才是与编译链路结合的（所以 `Component()` 不能传 `is` ）。

另外，虽然没有明说，有些特性指定了 `is` 时才能使用，比如组件需要递归引用自身的时候（毕竟你不可能在 using 里面放自身 defineComponent 的结果）。

**Comment by dhlolo** [comment]
答案我是接受的，但实际上如果真要上线，从应用开发者角度来说，写法上来说会显得有点多余，尤其是在react等框架 珠玉在前 的情况下，react中的jsx一开始也是非js原生支持的，加入一点单独的编译链路对提升开发体验还是很有帮助的。

**Comment by LastLeaf** [comment]
那就用 glass-easel-miniprogram-adapter 就可以了。核心模块不适合与编译链路耦合。
