### ISSUE TITLE
请问下版本更新机制，如何兼容老版本 PC 微信客户端？

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/glass-easel#76]

**Comment by LastLeaf** [comment]
glass-easel 不可用于旧版本微信客户端。换句话说， glass-easel 的新特性无法正常运行在这些客户端上，请慎重使用 glass-easel 特有的新特性。

**Comment by xiaweiss** [comment]
@LastLeaf 现在微信客户端有 8 个平台： iOS、Android、Mac、Windows，以及前述各平台的企业微信。
这 8 个平台的客户端版本号都不同，小程序基础库版本也不同。

请问下旧版本具体指什么呢？

**Comment by xiaweiss** [comment]
举个例子：
官方文档里标注的：[正在支持] glass-easel 下，暂不支持 WXS 事件响应。

这个目前会影响 PC 端 webview 渲染模式的页面，导致 WXS 写的手势滑动逻辑失效。

那么 PC 要怎么兼容呢？或者说等哪个版本才可以开启 glass-easel 切换到 skyline 呢？

**Comment by LastLeaf** [comment]
> @LastLeaf 现在微信客户端有 8 个平台： iOS、Android、Mac、Windows，以及前述各平台的企业微信。 这 8 个平台的客户端版本号都不同，小程序基础库版本也不同。
> 
> 请问下旧版本具体指什么呢？

简单来说就是非最新的客户端版本。一般情况下，新的基础库版本不会被应用到非最新的客户端版本上。

对于这个 case 来说，就是 glass-easel 的新特性不能在旧的客户端版本上使用。

**Comment by LastLeaf** [comment]
> 举个例子：
> 
> 官方文档里标注的：[正在支持] glass-easel 下，暂不支持 WXS 事件响应。
> 
> 这个目前会影响 PC 端 webview 渲染模式的页面，导致 WXS 写的手势滑动逻辑失效。
> 
> 那么 PC 要怎么兼容呢？或者说等哪个版本才可以开启 glass-easel 切换到 skyline 呢？

和相关同事了解了一下，现在应该是后台编译没有完全准备好，并不是客户端有问题。这个我们在 #78 追踪。

**Comment by xiaweiss** [comment]
明白了，我理解是这样
1. app.json 的配置 "componentFramework": "glass-easel"，可以直接配置上开启，不区分版本
2. glass-easel 提供的 wxml 相关的新语法，需要小程序基础库，目前最低要求 3.0.0（首个 release 版本），后续特性的按文档标注的基础库
3. 按[文档适配](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html)后，预期不会对基础库 3.0.0 以下老语法的 webview 渲染模式有影响。

第 3 点需要注意，已知问题：
1. wxml 里面的 \n，需要改写成 {{'\n'}} （建议文档里补充下）
2. wxs 事件响应问题 #78
