### ISSUE TITLE
开启 skyline 模式真机调试报 glass-easel component configs found in space

### ISSUE THREAD

**Issue by l-hammer** [wechat-miniprogram/glass-easel#79]
logs.ts:15 MiniProgramError
No any glass-easel component configs found in space, may be not a valid code package
Error: No any glass-easel component configs found in space, may be not a valid code package
@https://lib/WAServiceMainContext.js:1:1990207
@https://lib/WAServiceMainContext.js:1:1540207
@https://lib/WAServiceMainContext.js:1:843144
emit@https://lib/WAServiceMainContext.js:1:848189
@https://lib/WAServiceMainContext.js:1:849236
@https://lib/WAServiceMainContext.js:1:839516
emit@https://lib/WAServiceMainContext.js:1:355827
emit@[native code]
emit@https://lib/WAServiceMainContext.js:1:355446
subscribeHandler@https://lib/WAServiceMainContext.js:1:358932
@[native code]
dispatchBridgeMessages@https://lib/WAServiceMainContext.js:1:44479
@https://lib/WAServiceMainContext.js:1:2411607
@https://lib/WAServiceMainContext.js:1:44661
G@https://lib/WAServiceMainContext.js:1:307730
@https://lib/WAServiceMainContext.js:1:307952
k@https://lib/WAServiceMainContext.js:1:277429
@https://lib/WAServiceMainContext.js:1:291251
E@https://lib/WAServiceMainContext.js:1:291020
@https://lib/WAServiceMainContext.js:1:291058
p@https://lib/WAServiceMainContext.js:1:398554
@https://lib/WAServiceMainContext.js:1:386783
_onNativeTimer@
global code@

**Comment by xiaweiss** [comment]
skyline 模式真机调试一直都没支持

**Comment by LastLeaf** [comment]
不活跃了，关闭。
