### ISSUE TITLE
抽象节点不支持数据绑定。。

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/glass-easel#8]
纯内部状态的UI组件么？不能数据绑定的话，只是出于复用角度，个人感觉，几乎没什么实用性

**Comment by LastLeaf** [comment]
原本的设计主要是用来做小程序插件的。一个小程序组件可以简单地引用一个插件的组件（你可以理解为另一个 componentSpace 里的组件，而且那个 componentSpace 代码是完全分离的），但反过来，插件的组件没法引用小程序的组件。 generics 就是为这种情况提供了一个依赖逆转。

本质上说，它其实是给组件提供了一个“泛型”机制，利用类型参数来做复杂的抽象。

如果没有涉及复杂的三方开发或组件抽象，这个特性可能确实用不上就是了。
