### ISSUE TITLE
Methods' generic types are lost

### ISSUE THREAD

**Issue by ManiaciaChao** [wechat-miniprogram/glass-easel#81]
If we pass a `FunctionDeclaration` into definition API's field `methods` or  `methods()`, TypeScript will strip generic types from it. Here's an reproducible example.

```typescript
// wrong
glassEasel
  .registerBehavior({
    methods: {
      generic<T = any>(this: void, t: T) {
        return t
      },
    },
  })
  .getMethods()
  .generic<number>(11)
//         ^^^^^^ Expected 0 type arguments, but got 1.ts(2558)

// ok
const methods = {
  generic<T = any>(this: void, t: T) {
    return t
  },
}
glassEasel
  .registerBehavior({ methods: { ...methods } })
  .getMethods()
  .generic<number>(45)

```

**Comment by LastLeaf** [comment]
By the way, we do not encourage the use of methods in chaining API.

* A private (or exported) function in `init` can be used as an inner function (or event listener).
* If a method is designed to be called by other components, use trait behaviors.

**Comment by LastLeaf** [comment]
Seems not fixable. Closed.
