### ISSUE TITLE
skyline 这玩意用的脑壳疼哇, 文档能不能好好写写

### ISSUE THREAD

**Issue by l-hammer** [wechat-miniprogram/glass-easel#85]
各种动画、事件不生效，在 webview 下都是正常的。。。 组件和 webview 展示各种不一致。。。

**Comment by LastLeaf** [comment]
与 glass-easel 无关。据我所知，skyline 的组件实现与 webview 不同，部分特性并不支持，具体请查阅 skyline 的组件文档。

> 但请注意 glass-easel 只是小程序 SDK 中的组件框架部分（一个很小的部分，大体上对应于小程序文档中的“自定义组件”一章）。对于小程序其他部分的反馈，请前往 [微信开放社区](https://developers.weixin.qq.com/) 。

P.S. 请避免无助于项目发展的情绪性 issue 。
