### ISSUE TITLE
skyline 模式下 boundingClientRect 不执行

### ISSUE THREAD

**Issue by l-hammer** [wechat-miniprogram/glass-easel#86]
touchmove 事件中获取不到节点信息, webview 是正常的, 代码如下: 
const query = wx.createSelectorQuery().in(this);
      query
        .select('#ecs-slider')
        .boundingClientRect(function (res) {
          console.log('--- res', res);
        })
        .exec();
        
提示信息: An SelectorQuery call is ignored because no proper page or component is found. Please considering using `SelectorQuery.in` to specify a proper one. {type: "string", description: "An SelectorQuery call is ignored because no proper page or component is found. Please considering using `SelectorQuery.in` to specify a proper one.", value: "An SelectorQuery call is ignored because no proper page or component is found. Please considering using `SelectorQuery.in` to specify a proper one."}

**Comment by SgLy** [comment]
我这里没法复现：https://developers.weixin.qq.com/s/8hSEANmT7QKS

能给一个复现问题的片段查一下吗？

**Comment by LastLeaf** [comment]
不活跃了，关闭。
