### ISSUE TITLE
跨组件的模板片段中的new Function是代表框架将来也只是替换掉当前运行时的组件解析代码？而不会提供给应用开发者么

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/glass-easel#9]
还是只是在较长一段时间不会应用于线上小程序么？或者后面上线小程序会放开new Function的使用？

**Comment by dhlolo** [comment]
看起来目前阶段应该是一个类似小程序编译器和部分运行时组件解析逻辑的前端transform和simulate项目~

**Comment by LastLeaf** [comment]
这个其实只是文档上为了方便才这么写的。

无论如何，还是建议在构建期间编译而不是在运行期，这样可以节约启动时间。在小程序 SDK 里面也是构建期间编译的。
